### ISSUE TITLE
Curves/ellipses look jagged

### ISSUE THREAD

**Issue by APOS80** [gam17/QAD#41]
When theres time the curve/ellips function needs to be improved.

**Comment by gam17** [comment]
Hi Andreas,
   the number of segments componing a curve is calculated using the
parameters shown in the options.jpg image (see attached files).
As an example in the circles.jpg image:
- on the right, a circle using "maximum admitted error between a real
curve and the aproximated, segmented curve" = 0.1.
- on the left, the same circle using "maximum admitted error between a
real curve and the aproximated,sgmented curve" = 0.001.

From the QAD point of view having a fixed number of segments in a curve
doesn'make sense because the error between a real curve and the
aproximated, segmented curve must be in the predefined tolerance. Look
at the related QAD manual page in the page.jpg attached file for
details.

Thank you for making QAD a better plugin.

**Comment by gam17** [comment]
![page](https://user-images.githubusercontent.com/16491905/75853682-e7c0e700-5dee-11ea-981d-3702ba9ff7f9.jpg)
![circles](https://user-images.githubusercontent.com/16491905/75853693-e8f21400-5dee-11ea-8cc6-bfde8050b821.jpg)
![options](https://user-images.githubusercontent.com/16491905/75853695-e98aaa80-5dee-11ea-945d-b3ead66c4adc.jpg)

**Comment by APOS80** [comment]
I have problems changing the admitted error. 
It won’t accept “,” only “.” for decimal and I can’t seems to insert a period in that field, in Sweden we use comma for decimal.

**Comment by gam17** [comment]
Hi Andreas,
   QAD emulates Autocad as much as possible. For decimal separator
Autocad accepts "." only.
This is the reason QAD doesn't accepts "," for decimal separator.

gam17

**Comment by APOS80** [comment]
But as I’m on a Swedish keyboard I can’t get a “.”.

**Comment by APOS80** [comment]
If you could make it accept a “,” but transform it to a “.” it would work for everyone.

**Comment by gam17** [comment]
Hi Andreas,
   what do you mean <on a Swedish keyboard I can't get a “.”> ?
Your keyboard misses the "." key ?
I googled "Swedish keyboard" and all images show the "." key so I don't
understand...
Can you exaplain using other words ?
Thank you
gam17

**Comment by APOS80** [comment]
Pushing the “.” button doesn’t put a dot in the QAD settings. Pushing the comma button does put a comma in the field but QAD doesn’t like that.
